### ISSUE TITLE
无法识别interface.json的"pipeline_override"属性

### ISSUE THREAD

**Issue by ywkf** [overflow65537/MFW-PyQt6#19]
你好，运行时"pipeline_override"属性似乎无法起作用

**Comment by overflow65537** [comment]
debug/maa.log发一下

**Comment by ywkf** [comment]
[maa.log](https://github.com/user-attachments/files/18251507/maa.log)

**Comment by overflow65537** [comment]
[v1.1.2](https://github.com/overflow65537/MFW-PyQt6/releases/tag/v1.1.2)
